### ISSUE TITLE
Version bump for new release?

### ISSUE THREAD

**Issue by sveinugu** [galaxyproject/gx-it-proxy#16]
I believe the version of `gx-it-proxy` should be bumped both here and in galaxy requirements to get both https://github.com/galaxyproject/gx-it-proxy/pull/14 and https://github.com/galaxyproject/gx-it-proxy/pull/15 into the new release (if it is not too late)?

See also https://github.com/galaxyproject/gravity/issues/92#issuecomment-1427635721 for coordinating with a version bump of gravity.

**Comment by natefoo** [comment]
@jmchilton you own the package in npm, can you push a new release (or add someone else/a bot so that we can do GHA releases)?

**Comment by jmchilton** [comment]
I've pushed a new version. If anyone has npm usernames they'd like me to add for maintaience ... let me know.

**Comment by mvdbeek** [comment]
@jmchilton can you add my account ? it's `mvdbeek`

**Comment by sveinugu** [comment]
> @jmchilton can you add my account ? it's `mvdbeek`

Sorry to bug you again, @jmchilton, but if you can fix this, it will help us at the Biohackathon!

**Comment by jmchilton** [comment]
Added - sorry about that.

**Comment by mvdbeek** [comment]
Thanks @jmchilton, published 0.0.6 @ https://www.npmjs.com/package/gx-it-proxy/v/0.0.6
